// <auto-generated />
using System;
using AspNetCore.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace V_Store_beck.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330183931_FixPending")]
    partial class FixPending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCore.WebAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScreenshotId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenshotId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 52,
                            GPA = 10.5,
                            Name = "Elden Ring",
                            Photo = "eldenring.png",
                            Price = 59.99m,
                            Surname = "FromSoftware"
                        },
                        new
                        {
                            Id = 2,
                            Age = 70,
                            GPA = 9.8000000000000007,
                            Name = "Cyberpunk 2077",
                            Photo = "cyberpunk2077.png",
                            Price = 49.99m,
                            Surname = "CD Projekt"
                        },
                        new
                        {
                            Id = 3,
                            Age = 15,
                            GPA = 9.5,
                            Name = "Dota 2",
                            Photo = "dota2.png",
                            Price = 0m,
                            Surname = "Valve"
                        },
                        new
                        {
                            Id = 4,
                            Age = 20,
                            GPA = 9.6999999999999993,
                            Name = "Counter-Strike: Global Offensive",
                            Photo = "csgo.png",
                            Price = 0m,
                            Surname = "Valve"
                        },
                        new
                        {
                            Id = 5,
                            Age = 50,
                            GPA = 9.9000000000000004,
                            Name = "The Witcher 3: Wild Hunt",
                            Photo = "witcher3.png",
                            Price = 39.99m,
                            Surname = "CD Projekt"
                        },
                        new
                        {
                            Id = 6,
                            Age = 15,
                            GPA = 9.5999999999999996,
                            Name = "Hades",
                            Photo = "hades.png",
                            Price = 24.99m,
                            Surname = "Supergiant Games"
                        },
                        new
                        {
                            Id = 7,
                            Age = 1,
                            GPA = 9.4000000000000004,
                            Name = "Stardew Valley",
                            Photo = "stardew.png",
                            Price = 14.99m,
                            Surname = "ConcernedApe"
                        },
                        new
                        {
                            Id = 8,
                            Age = 0,
                            GPA = 9.3000000000000007,
                            Name = "Terraria",
                            Photo = "terraria.png",
                            Price = 9.99m,
                            Surname = "Re-Logic"
                        },
                        new
                        {
                            Id = 9,
                            Age = 95,
                            GPA = 10.300000000000001,
                            Name = "Red Dead Redemption 2",
                            Photo = "rdr2.png",
                            Price = 59.99m,
                            Surname = "Rockstar Games"
                        },
                        new
                        {
                            Id = 10,
                            Age = 99,
                            GPA = 10.4,
                            Name = "The Legend of Zelda: BoTW",
                            Photo = "zelda_botw.png",
                            Price = 59.99m,
                            Surname = "Nintendo"
                        },
                        new
                        {
                            Id = 11,
                            Age = 93,
                            GPA = 9.1999999999999993,
                            Name = "Grand Theft Auto V",
                            Photo = "gtav.png",
                            Price = 29.99m,
                            Surname = "Rockstar Games"
                        },
                        new
                        {
                            Id = 12,
                            Age = 100,
                            GPA = 9.0,
                            Name = "Minecraft",
                            Photo = "minecraft.png",
                            Price = 26.99m,
                            Surname = "Mojang"
                        },
                        new
                        {
                            Id = 13,
                            Age = 94,
                            GPA = 10.0,
                            Name = "Half-Life 2",
                            Photo = "half_life2.png",
                            Price = 9.99m,
                            Surname = "Valve"
                        },
                        new
                        {
                            Id = 14,
                            Age = 90,
                            GPA = 9.8000000000000007,
                            Name = "Portal 2",
                            Photo = "portal2.png",
                            Price = 9.99m,
                            Surname = "Valve"
                        },
                        new
                        {
                            Id = 15,
                            Age = 96,
                            GPA = 9.5999999999999996,
                            Name = "The Elder Scrolls V: Skyrim",
                            Photo = "skyrim.png",
                            Price = 39.99m,
                            Surname = "Bethesda Game Studios"
                        },
                        new
                        {
                            Id = 16,
                            Age = 88,
                            GPA = 9.9000000000000004,
                            Name = "Mass Effect 2",
                            Photo = "masseffect2.png",
                            Price = 19.99m,
                            Surname = "BioWare"
                        },
                        new
                        {
                            Id = 17,
                            Age = 82,
                            GPA = 9.4000000000000004,
                            Name = "Diablo II",
                            Photo = "diablo2.png",
                            Price = 19.99m,
                            Surname = "Blizzard Entertainment"
                        },
                        new
                        {
                            Id = 18,
                            Age = 85,
                            GPA = 9.0999999999999996,
                            Name = "Doom (1993)",
                            Photo = "doom93.png",
                            Price = 4.99m,
                            Surname = "id Software"
                        },
                        new
                        {
                            Id = 19,
                            Age = 87,
                            GPA = 9.6999999999999993,
                            Name = "Resident Evil 4",
                            Photo = "re4.png",
                            Price = 29.99m,
                            Surname = "Capcom"
                        },
                        new
                        {
                            Id = 20,
                            Age = 97,
                            GPA = 10.1,
                            Name = "Super Mario World",
                            Photo = "smw.png",
                            Price = 19.99m,
                            Surname = "Nintendo EAD"
                        },
                        new
                        {
                            Id = 21,
                            Age = 100,
                            GPA = 8.9000000000000004,
                            Name = "Tetris",
                            Photo = "tetris.png",
                            Price = 4.99m,
                            Surname = "Alexey Pajitnov"
                        },
                        new
                        {
                            Id = 22,
                            Age = 95,
                            GPA = 9.5,
                            Name = "Final Fantasy VII",
                            Photo = "ff7.png",
                            Price = 15.99m,
                            Surname = "Square"
                        },
                        new
                        {
                            Id = 23,
                            Age = 89,
                            GPA = 9.6999999999999993,
                            Name = "Metal Gear Solid",
                            Photo = "mgs.png",
                            Price = 19.99m,
                            Surname = "Konami"
                        },
                        new
                        {
                            Id = 24,
                            Age = 94,
                            GPA = 9.3000000000000007,
                            Name = "World of Warcraft",
                            Photo = "wow.png",
                            Price = 14.99m,
                            Surname = "Blizzard Entertainment"
                        },
                        new
                        {
                            Id = 25,
                            Age = 86,
                            GPA = 9.5999999999999996,
                            Name = "BioShock",
                            Photo = "bioshock.png",
                            Price = 19.99m,
                            Surname = "Irrational Games"
                        },
                        new
                        {
                            Id = 26,
                            Age = 81,
                            GPA = 9.0,
                            Name = "StarCraft",
                            Photo = "starcraft.png",
                            Price = 14.99m,
                            Surname = "Blizzard Entertainment"
                        },
                        new
                        {
                            Id = 27,
                            Age = 78,
                            GPA = 8.8000000000000007,
                            Name = "SimCity 2000",
                            Photo = "simcity2000.png",
                            Price = 9.99m,
                            Surname = "Maxis"
                        },
                        new
                        {
                            Id = 28,
                            Age = 97,
                            GPA = 10.4,
                            Name = "Baldur's Gate 3",
                            Photo = "bg3.png",
                            Price = 59.99m,
                            Surname = "Larian Studios"
                        },
                        new
                        {
                            Id = 29,
                            Age = 84,
                            GPA = 9.5,
                            Name = "Hollow Knight",
                            Photo = "hollow_knight.png",
                            Price = 14.99m,
                            Surname = "Team Cherry"
                        },
                        new
                        {
                            Id = 30,
                            Age = 88,
                            GPA = 9.6999999999999993,
                            Name = "Shadow of the Colossus",
                            Photo = "sotc.png",
                            Price = 19.99m,
                            Surname = "Team Ico"
                        },
                        new
                        {
                            Id = 31,
                            Age = 91,
                            GPA = 9.0999999999999996,
                            Name = "Pokemon Red/Blue",
                            Photo = "pokemon_rb.png",
                            Price = 9.99m,
                            Surname = "Game Freak"
                        },
                        new
                        {
                            Id = 32,
                            Age = 93,
                            GPA = 10.0,
                            Name = "Super Metroid",
                            Photo = "super_metroid.png",
                            Price = 9.99m,
                            Surname = "Nintendo R&D1"
                        },
                        new
                        {
                            Id = 33,
                            Age = 95,
                            GPA = 9.9000000000000004,
                            Name = "The Last of Us",
                            Photo = "tlou.png",
                            Price = 39.99m,
                            Surname = "Naughty Dog"
                        },
                        new
                        {
                            Id = 34,
                            Age = 87,
                            GPA = 9.5,
                            Name = "Castlevania: SotN",
                            Photo = "sotn.png",
                            Price = 9.99m,
                            Surname = "Konami"
                        },
                        new
                        {
                            Id = 35,
                            Age = 80,
                            GPA = 9.3000000000000007,
                            Name = "Monkey Island 2",
                            Photo = "mi2.png",
                            Price = 9.99m,
                            Surname = "LucasArts"
                        },
                        new
                        {
                            Id = 36,
                            Age = 86,
                            GPA = 9.5999999999999996,
                            Name = "Uncharted 2: Among Thieves",
                            Photo = "uncharted2.png",
                            Price = 19.99m,
                            Surname = "Naughty Dog"
                        },
                        new
                        {
                            Id = 37,
                            Age = 79,
                            GPA = 9.4000000000000004,
                            Name = "Dishonored",
                            Photo = "dishonored.png",
                            Price = 19.99m,
                            Surname = "Arkane Studios"
                        },
                        new
                        {
                            Id = 38,
                            Age = 91,
                            GPA = 10.1,
                            Name = "Disco Elysium",
                            Photo = "disco_elysium.png",
                            Price = 29.99m,
                            Surname = "ZA/UM"
                        },
                        new
                        {
                            Id = 39,
                            Age = 83,
                            GPA = 9.1999999999999993,
                            Name = "Fallout: New Vegas",
                            Photo = "new_vegas.png",
                            Price = 9.99m,
                            Surname = "Obsidian Entertainment"
                        },
                        new
                        {
                            Id = 40,
                            Age = 85,
                            GPA = 9.5,
                            Name = "Deus Ex",
                            Photo = "deus_ex.png",
                            Price = 9.99m,
                            Surname = "Ion Storm"
                        },
                        new
                        {
                            Id = 41,
                            Age = 70,
                            GPA = 9.0,
                            Name = "Civilization VI",
                            Photo = "civ6.png",
                            Price = 29.99m,
                            Surname = "Firaxis Games"
                        },
                        new
                        {
                            Id = 42,
                            Age = 68,
                            GPA = 8.9000000000000004,
                            Name = "Rocket League",
                            Photo = "rocket_league.png",
                            Price = 0m,
                            Surname = "Psyonix"
                        },
                        new
                        {
                            Id = 43,
                            Age = 75,
                            GPA = 9.3000000000000007,
                            Name = "Inside",
                            Photo = "inside.png",
                            Price = 19.99m,
                            Surname = "Playdead"
                        },
                        new
                        {
                            Id = 44,
                            Age = 90,
                            GPA = 9.5999999999999996,
                            Name = "Street Fighter II",
                            Photo = "sf2.png",
                            Price = 14.99m,
                            Surname = "Capcom"
                        },
                        new
                        {
                            Id = 45,
                            Age = 72,
                            GPA = 8.6999999999999993,
                            Name = "The Sims",
                            Photo = "the_sims.png",
                            Price = 19.99m,
                            Surname = "Maxis"
                        },
                        new
                        {
                            Id = 46,
                            Age = 78,
                            GPA = 9.8000000000000007,
                            Name = "Doom Eternal",
                            Photo = "doom_eternal.png",
                            Price = 39.99m,
                            Surname = "id Software"
                        },
                        new
                        {
                            Id = 47,
                            Age = 76,
                            GPA = 9.4000000000000004,
                            Name = "Journey",
                            Photo = "journey.png",
                            Price = 14.99m,
                            Surname = "Thatgamecompany"
                        },
                        new
                        {
                            Id = 48,
                            Age = 89,
                            GPA = 9.9000000000000004,
                            Name = "Outer Wilds",
                            Photo = "outer_wilds.png",
                            Price = 24.99m,
                            Surname = "Mobius Digital"
                        });
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.GlobalMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GlobalMessages");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000m,
                            Email = "admin@vstore.com",
                            PasswordHash = "$2a$11$KIX7YB1r0A2Gx6GxVqQe6OLt6qj1Q6i8zB8uYwYh9a1b2c3d4e5fO",
                            Photo = "User.png",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.CartItem", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCore.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Comment", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.Screenshot", "Screenshot")
                        .WithMany()
                        .HasForeignKey("ScreenshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screenshot");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.GlobalMessage", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Message", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AspNetCore.WebAPI.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Order", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.OrderItem", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCore.WebAPI.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Screenshot", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.UserGame", b =>
                {
                    b.HasOne("AspNetCore.WebAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCore.WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
